version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 5093
      MYSQL_DATABASE: buysell
    ports:
      - "3307:3306"
    networks:
      - buysell-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/buysell
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 5093
    depends_on:
      - mysql-db
    networks:
      - buysell-network

networks:
  buysell-network:
    driver: bridge

volumes:
  mysql-data:
